# Generated by Django 2.2.4 on 2019-10-20 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('med_name', models.TextField()),
                ('hour', models.TextField()),
                ('minute', models.TimeField()),
                ('PM', models.BooleanField()),
            ],
        ),
    ]
