# Generated by Django 2.2 on 2019-10-22 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('time', models.TimeField()),
                ('repeat', models.PositiveIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Reminder',
        ),
    ]
