# Generated by Django 2.2 on 2019-10-22 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0002_auto_20191022_1657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reminderdb',
            old_name='time',
            new_name='hour',
        ),
    ]
