# Generated by Django 2.2 on 2019-10-22 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reminder', '0003_auto_20191022_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminderdb',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reminderdb',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
