# Generated by Django 2.2 on 2019-10-26 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0006_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminderdb',
            name='timezone',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
