# Generated by Django 2.2 on 2019-10-26 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0009_auto_20191026_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.PositiveIntegerField(),
        ),
    ]
